using System;
using System.Collections.Generic;
using HarmonyLib;
using Valheim.CustomRaids.Configuration;

namespace Valheim.CustomRaids.Datamining;

[HarmonyPatch]
internal static class CharacterGlobalKeyMiner
{
    [HarmonyPatch(typeof(ZoneSystem), nameof(ZoneSystem.Start))]
    [HarmonyPostfix]
    private static void PrintCreatureKeys()
    {
        if (ConfigurationManager.GeneralConfig?.WriteGlobalKeyDataToDisk.Value != true)
        {
            return;
        }

        List<string> creatureKeys = new()
        {
            $"# This file was auto-generated by Custom Raids {CustomRaidPlugin.Version} at {DateTimeOffset.UtcNow.ToString("u")}, with Valheim '{Version.CurrentVersion.m_major}.{Version.CurrentVersion.m_minor}.{Version.CurrentVersion.m_patch}'.",
            $"# The entries listed here were extracted at runtime. " +
            $"# It shows the prefab names of creatures that will assign globalkeys and playerkeys when defeated, with the actual key listed next to them.",
            $"# The file is intended for investigation and is not scanned by Custom Raids, any changes done will therefore have no effect.",
            ""
        };

        foreach (var prefab in ZNetScene.instance.m_prefabs)
        {
            if (prefab.TryGetComponent<Character>(out Character character))
            {
                if (!string.IsNullOrWhiteSpace(character.m_defeatSetGlobalKey))
                {
                    creatureKeys.Add($"{prefab.name}: {character.m_defeatSetGlobalKey}");
                }
            }
        }

        DebugFileWriter.WriteFile(
            creatureKeys,
            "custom_raids.creature_keys.txt",
            "list of creatures and the globalkey set upon defeat");
    }
}

